import numpy as np

In [4]:
import numpy as np
ar = np.array([1, 2, 3, 4, 5])
# Multiique todos os elementos por 10.
m = ar * 10
m
# Calcule a média dos valores.
media  =  np.mean(ar)
media
# Substitua os números pares por -1.
x = -1
r = ar [ar % 2 == 0 ] = x
ar


array([ 1, -1,  3, -1,  5])

In [15]:
import numpy as np 
array_2d = np.random.randint(0, 100, size=(5, 5))
print(array_2d)

soma = sum(array_2d[0])
m = soma /len(array_2d[0])
print(m)
soma = sum(array_2d[1])
m = soma /len(array_2d[1])
print(m)

soma = sum(array_2d[2])
m = soma /len(array_2d[2])
print(m)

soma = sum(array_2d[3])
m = soma /len(array_2d[3])
print(m)

soma = sum(array_2d[4])
m = soma /len(array_2d[4])
print(m)

maxi = max(array_2d)
print(maxi)

mini = min(array_2d)
print(mini)



[[65 62 76 18  0]
 [ 2  0 23 62 54]
 [ 2 72 75 47 41]
 [73  9 18 47 35]
 [ 0 24 12 52 82]]
44.2
28.2
47.4
36.4
34.0


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()