import numpy as np

In [4]:
import numpy as np
ar = np.array([1, 2, 3, 4, 5])
# Multiique todos os elementos por 10.
m = ar * 10
m
# Calcule a média dos valores.
media  =  np.mean(ar)
media
# Substitua os números pares por -1.
x = -1
r = ar [ar % 2 == 0 ] = x
ar


array([ 1, -1,  3, -1,  5])

In [3]:
import numpy as np 
array_2d = np.random.randint(0, 100, size=(5, 5))
print(array_2d)

soma = sum(array_2d[0])
m = soma /len(array_2d[0])
print(m)
soma = sum(array_2d[1])
m = soma /len(array_2d[1])
print(m)

soma = sum(array_2d[2])
m = soma /len(array_2d[2])
print(m)

soma = sum(array_2d[3])
m = soma /len(array_2d[3])
print(m)

soma = sum(array_2d[4])
m = soma /len(array_2d[4])
print(m)




[[24 77 63  9 11]
 [72 41 20 69 14]
 [41 62 39 13 84]
 [89 65 96 72 60]
 [71 19 26 97 68]]
36.8
43.2
47.8
76.4
56.2
